
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.util.HashMap ///

open class HashMap: /* java.util.AbstractMap */ UnclassedObject {

    public convenience init?( casting object: JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var HashMapJNIClass: jclass?

    /// private static final long java.util.HashMap.serialVersionUID

    /// static final int java.util.HashMap.DEFAULT_INITIAL_CAPACITY

    /// static final int java.util.HashMap.MAXIMUM_CAPACITY

    /// static final float java.util.HashMap.DEFAULT_LOAD_FACTOR

    /// static final int java.util.HashMap.TREEIFY_THRESHOLD

    /// static final int java.util.HashMap.UNTREEIFY_THRESHOLD

    /// static final int java.util.HashMap.MIN_TREEIFY_CAPACITY

    /// transient java.util.HashMap$Node[] java.util.HashMap.table

    /// transient java.util.Set java.util.HashMap.entrySet

    /// transient int java.util.HashMap.size

    /// transient int java.util.HashMap.modCount

    /// int java.util.HashMap.threshold

    /// final float java.util.HashMap.loadFactor

    /// transient java.util.Set java.util.AbstractMap.keySet

    /// transient java.util.Collection java.util.AbstractMap.values

    /// public java.util.HashMap(int)

    private static var new_MethodID_1: jmethodID?

    public convenience init( initialCapacity: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: initialCapacity, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/HashMap", classCache: &HashMap.HashMapJNIClass, methodSig: "(I)V", methodCache: &HashMap.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _initialCapacity: Int ) {
        self.init( initialCapacity: _initialCapacity )
    }

    /// public java.util.HashMap()

    private static var new_MethodID_2: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "java/util/HashMap", classCache: &HashMap.HashMapJNIClass, methodSig: "()V", methodCache: &HashMap.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public java.util.HashMap(java.util.Map)

    private static var new_MethodID_3: jmethodID?

    public convenience init( m: JavaMap? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: m, mapClass: "java/util/Map", locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/HashMap", classCache: &HashMap.HashMapJNIClass, methodSig: "(Ljava/util/Map;)V", methodCache: &HashMap.new_MethodID_3, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _m: JavaMap? ) {
        self.init( m: _m )
    }

    /// public java.util.HashMap(int,float)

    private static var new_MethodID_4: jmethodID?

    public convenience init( initialCapacity: Int, loadFactor: Float ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: initialCapacity, locals: &__locals )
        __args[1] = JNIType.toJava( value: loadFactor, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/util/HashMap", classCache: &HashMap.HashMapJNIClass, methodSig: "(IF)V", methodCache: &HashMap.new_MethodID_4, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _initialCapacity: Int, _ _loadFactor: Float ) {
        self.init( initialCapacity: _initialCapacity, loadFactor: _loadFactor )
    }

    /// public java.lang.Object java.util.HashMap.remove(java.lang.Object)

    /// public boolean java.util.HashMap.remove(java.lang.Object,java.lang.Object)

    private static var remove_MethodID_5: jmethodID?

    open func remove( arg0: JavaObject?, arg1: JavaObject? ) -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1 != nil ? arg1! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "remove", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;)Z", methodCache: &HashMap.remove_MethodID_5, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Bool(), from: __return )
    }

    open func remove( _ _arg0: JavaObject?, _ _arg1: JavaObject? ) -> Bool {
        return remove( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.lang.Object java.util.HashMap.get(java.lang.Object)

    /// public java.lang.Object java.util.HashMap.put(java.lang.Object,java.lang.Object)

    /// static final int java.util.HashMap.hash(java.lang.Object)

    /// public java.util.Collection java.util.HashMap.values()

    /// public java.lang.Object java.util.HashMap.clone()

    private static var clone_MethodID_6: jmethodID?

    override open func clone() -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "clone", methodSig: "()Ljava/lang/Object;", methodCache: &HashMap.clone_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }


    /// public void java.util.HashMap.clear()

    /// public boolean java.util.HashMap.isEmpty()

    /// public boolean java.util.HashMap.replace(java.lang.Object,java.lang.Object,java.lang.Object)

    private static var replace_MethodID_7: jmethodID?

    open func replace( arg0: JavaObject?, arg1: JavaObject?, arg2: JavaObject? ) -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1 != nil ? arg1! as JNIObject : nil, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2 != nil ? arg2! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "replace", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z", methodCache: &HashMap.replace_MethodID_7, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Bool(), from: __return )
    }

    open func replace( _ _arg0: JavaObject?, _ _arg1: JavaObject?, _ _arg2: JavaObject? ) -> Bool {
        return replace( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// public java.lang.Object java.util.HashMap.replace(java.lang.Object,java.lang.Object)

    private static var replace_MethodID_8: jmethodID?

    open func replace( arg0: JavaObject?, arg1: JavaObject? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1 != nil ? arg1! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "replace", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &HashMap.replace_MethodID_8, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func replace( _ _arg0: JavaObject?, _ _arg1: JavaObject? ) -> JavaObject! {
        return replace( arg0: _arg0, arg1: _arg1 )
    }

    /// public void java.util.HashMap.replaceAll(java.util.function.BiFunction)

    private static var replaceAll_MethodID_9: jmethodID?

    open func replaceAll( arg0: /* java.util.function.BiFunction */ UnclassedProtocol? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "replaceAll", methodSig: "(Ljava/util/function/BiFunction;)V", methodCache: &HashMap.replaceAll_MethodID_9, args: &__args, locals: &__locals )
    }

    open func replaceAll( _ _arg0: /* java.util.function.BiFunction */ UnclassedProtocol? ) {
        replaceAll( arg0: _arg0 )
    }

    /// public int java.util.HashMap.size()

    /// public java.util.Set java.util.HashMap.entrySet()

    /// public void java.util.HashMap.putAll(java.util.Map)

    /// public java.lang.Object java.util.HashMap.putIfAbsent(java.lang.Object,java.lang.Object)

    private static var putIfAbsent_MethodID_10: jmethodID?

    open func putIfAbsent( arg0: JavaObject?, arg1: JavaObject? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1 != nil ? arg1! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "putIfAbsent", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &HashMap.putIfAbsent_MethodID_10, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func putIfAbsent( _ _arg0: JavaObject?, _ _arg1: JavaObject? ) -> JavaObject! {
        return putIfAbsent( arg0: _arg0, arg1: _arg1 )
    }

    /// private void java.util.HashMap.readObject(java.io.ObjectInputStream) throws java.io.IOException,java.lang.ClassNotFoundException

    /// private void java.util.HashMap.writeObject(java.io.ObjectOutputStream) throws java.io.IOException

    /// public java.util.Set java.util.HashMap.keySet()

    private static var keySet_MethodID_11: jmethodID?

    open func keySet() -> JavaSet! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "keySet", methodSig: "()Ljava/util/Set;", methodCache: &HashMap.keySet_MethodID_11, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaSetForward( javaObject: __return ) : nil
    }


    /// final float java.util.HashMap.loadFactor()

    /// public boolean java.util.HashMap.containsValue(java.lang.Object)

    /// public boolean java.util.HashMap.containsKey(java.lang.Object)

    /// public java.lang.Object java.util.HashMap.getOrDefault(java.lang.Object,java.lang.Object)

    private static var getOrDefault_MethodID_12: jmethodID?

    open func getOrDefault( arg0: JavaObject?, arg1: JavaObject? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1 != nil ? arg1! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getOrDefault", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &HashMap.getOrDefault_MethodID_12, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func getOrDefault( _ _arg0: JavaObject?, _ _arg1: JavaObject? ) -> JavaObject! {
        return getOrDefault( arg0: _arg0, arg1: _arg1 )
    }

    /// public void java.util.HashMap.forEach(java.util.function.BiConsumer)

    private static var forEach_MethodID_13: jmethodID?

    open func forEach( arg0: /* java.util.function.BiConsumer */ UnclassedProtocol? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "forEach", methodSig: "(Ljava/util/function/BiConsumer;)V", methodCache: &HashMap.forEach_MethodID_13, args: &__args, locals: &__locals )
    }

    open func forEach( _ _arg0: /* java.util.function.BiConsumer */ UnclassedProtocol? ) {
        forEach( arg0: _arg0 )
    }

    /// public java.lang.Object java.util.HashMap.computeIfAbsent(java.lang.Object,java.util.function.Function)

    private static var computeIfAbsent_MethodID_14: jmethodID?

    open func computeIfAbsent( arg0: JavaObject?, arg1: /* java.util.function.Function */ UnclassedProtocol? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "computeIfAbsent", methodSig: "(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object;", methodCache: &HashMap.computeIfAbsent_MethodID_14, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func computeIfAbsent( _ _arg0: JavaObject?, _ _arg1: /* java.util.function.Function */ UnclassedProtocol? ) -> JavaObject! {
        return computeIfAbsent( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.lang.Object java.util.HashMap.computeIfPresent(java.lang.Object,java.util.function.BiFunction)

    private static var computeIfPresent_MethodID_15: jmethodID?

    open func computeIfPresent( arg0: JavaObject?, arg1: /* java.util.function.BiFunction */ UnclassedProtocol? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "computeIfPresent", methodSig: "(Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;", methodCache: &HashMap.computeIfPresent_MethodID_15, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func computeIfPresent( _ _arg0: JavaObject?, _ _arg1: /* java.util.function.BiFunction */ UnclassedProtocol? ) -> JavaObject! {
        return computeIfPresent( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.lang.Object java.util.HashMap.compute(java.lang.Object,java.util.function.BiFunction)

    private static var compute_MethodID_16: jmethodID?

    open func compute( arg0: JavaObject?, arg1: /* java.util.function.BiFunction */ UnclassedProtocol? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "compute", methodSig: "(Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;", methodCache: &HashMap.compute_MethodID_16, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func compute( _ _arg0: JavaObject?, _ _arg1: /* java.util.function.BiFunction */ UnclassedProtocol? ) -> JavaObject! {
        return compute( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.lang.Object java.util.HashMap.merge(java.lang.Object,java.lang.Object,java.util.function.BiFunction)

    private static var merge_MethodID_17: jmethodID?

    open func merge( arg0: JavaObject?, arg1: JavaObject?, arg2: /* java.util.function.BiFunction */ UnclassedProtocol? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1 != nil ? arg1! as JNIObject : nil, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "merge", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;", methodCache: &HashMap.merge_MethodID_17, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func merge( _ _arg0: JavaObject?, _ _arg1: JavaObject?, _ _arg2: /* java.util.function.BiFunction */ UnclassedProtocol? ) -> JavaObject! {
        return merge( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// final int java.util.HashMap.capacity()

    /// static java.lang.Class java.util.HashMap.comparableClassFor(java.lang.Object)

    /// static int java.util.HashMap.compareComparables(java.lang.Class,java.lang.Object,java.lang.Object)

    /// static final int java.util.HashMap.tableSizeFor(int)

    /// final void java.util.HashMap.putMapEntries(java.util.Map,boolean)

    /// final java.util.HashMap$Node java.util.HashMap.getNode(int,java.lang.Object)

    /// final java.lang.Object java.util.HashMap.putVal(int,java.lang.Object,java.lang.Object,boolean,boolean)

    /// final java.util.HashMap$Node[] java.util.HashMap.resize()

    /// final void java.util.HashMap.treeifyBin(java.util.HashMap$Node[],int)

    /// final java.util.HashMap$Node java.util.HashMap.removeNode(int,java.lang.Object,java.lang.Object,boolean,boolean)

    /// java.util.HashMap$Node java.util.HashMap.newNode(int,java.lang.Object,java.lang.Object,java.util.HashMap$Node)

    /// java.util.HashMap$Node java.util.HashMap.replacementNode(java.util.HashMap$Node,java.util.HashMap$Node)

    /// java.util.HashMap$TreeNode java.util.HashMap.newTreeNode(int,java.lang.Object,java.lang.Object,java.util.HashMap$Node)

    /// java.util.HashMap$TreeNode java.util.HashMap.replacementTreeNode(java.util.HashMap$Node,java.util.HashMap$Node)

    /// void java.util.HashMap.reinitialize()

    /// void java.util.HashMap.afterNodeAccess(java.util.HashMap$Node)

    /// void java.util.HashMap.afterNodeInsertion(boolean)

    /// void java.util.HashMap.afterNodeRemoval(java.util.HashMap$Node)

    /// void java.util.HashMap.internalWriteEntries(java.io.ObjectOutputStream) throws java.io.IOException

    /// In declared protocol but not defined.. ///

    /// public abstract boolean java.util.Map.equals(java.lang.Object)

    private static var equals_MethodID_18: jmethodID?

    override open func equals( arg0: JavaObject? ) -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "equals", methodSig: "(Ljava/lang/Object;)Z", methodCache: &HashMap.equals_MethodID_18, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Bool(), from: __return )
    }

    override open func equals( _ _arg0: JavaObject? ) -> Bool {
        return equals( arg0: _arg0 )
    }

    /// public abstract java.lang.Object java.util.Map.get(java.lang.Object)

    private static var get_MethodID_19: jmethodID?

    open func get( arg0: JavaObject? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "get", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &HashMap.get_MethodID_19, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func get( _ _arg0: JavaObject? ) -> JavaObject! {
        return get( arg0: _arg0 )
    }

    /// public abstract java.lang.Object java.util.Map.remove(java.lang.Object)

    private static var remove_MethodID_20: jmethodID?

    open func remove( arg0: JavaObject? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "remove", methodSig: "(Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &HashMap.remove_MethodID_20, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func remove( _ _arg0: JavaObject? ) -> JavaObject! {
        return remove( arg0: _arg0 )
    }

    /// public abstract boolean java.util.Map.containsValue(java.lang.Object)

    private static var containsValue_MethodID_21: jmethodID?

    open func containsValue( arg0: JavaObject? ) -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "containsValue", methodSig: "(Ljava/lang/Object;)Z", methodCache: &HashMap.containsValue_MethodID_21, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Bool(), from: __return )
    }

    open func containsValue( _ _arg0: JavaObject? ) -> Bool {
        return containsValue( arg0: _arg0 )
    }

    /// public abstract int java.util.Map.hashCode()

    /// public abstract java.util.Collection java.util.Map.values()

    /// public abstract void java.util.Map.putAll(java.util.Map)

    private static var putAll_MethodID_22: jmethodID?

    open func putAll( arg0: JavaMap? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0, mapClass: "java/util/Map", locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "putAll", methodSig: "(Ljava/util/Map;)V", methodCache: &HashMap.putAll_MethodID_22, args: &__args, locals: &__locals )
    }

    open func putAll( _ _arg0: JavaMap? ) {
        putAll( arg0: _arg0 )
    }

    /// public abstract void java.util.Map.clear()

    /// public abstract boolean java.util.Map.isEmpty()

    /// public abstract boolean java.util.Map.containsKey(java.lang.Object)

    private static var containsKey_MethodID_23: jmethodID?

    open func containsKey( arg0: JavaObject? ) -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "containsKey", methodSig: "(Ljava/lang/Object;)Z", methodCache: &HashMap.containsKey_MethodID_23, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: Bool(), from: __return )
    }

    open func containsKey( _ _arg0: JavaObject? ) -> Bool {
        return containsKey( arg0: _arg0 )
    }

    /// public abstract java.lang.Object java.util.Map.put(java.lang.Object,java.lang.Object)

    private static var put_MethodID_24: jmethodID?

    open func put( arg0: JavaObject?, arg1: JavaObject? ) -> JavaObject! {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: arg0 != nil ? arg0! as JNIObject : nil, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1 != nil ? arg1! as JNIObject : nil, locals: &__locals )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "put", methodSig: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", methodCache: &HashMap.put_MethodID_24, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }

    open func put( _ _arg0: JavaObject?, _ _arg1: JavaObject? ) -> JavaObject! {
        return put( arg0: _arg0, arg1: _arg1 )
    }

    /// public abstract java.util.Set java.util.Map.entrySet()

    /// public abstract int java.util.Map.size()

}

