
/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.lang.Thread ///

open class JavaThread: JavaObject, Runnable {

    public convenience init?( casting object: JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var JavaThreadJNIClass: jclass?

    /// private static final java.lang.StackTraceElement[] java.lang.Thread.EMPTY_STACK_TRACE

    /// public static final int java.lang.Thread.MAX_PRIORITY

    private static var MAX_PRIORITY_FieldID: jfieldID?

    open static var MAX_PRIORITY: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "MAX_PRIORITY", fieldType: "I", fieldCache: &MAX_PRIORITY_FieldID, className: "java/lang/Thread", classCache: &JavaThreadJNIClass )
            return Int(__value)
        }
    }

    /// public static final int java.lang.Thread.MIN_PRIORITY

    private static var MIN_PRIORITY_FieldID: jfieldID?

    open static var MIN_PRIORITY: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "MIN_PRIORITY", fieldType: "I", fieldCache: &MIN_PRIORITY_FieldID, className: "java/lang/Thread", classCache: &JavaThreadJNIClass )
            return Int(__value)
        }
    }

    /// public static final int java.lang.Thread.NORM_PRIORITY

    private static var NORM_PRIORITY_FieldID: jfieldID?

    open static var NORM_PRIORITY: Int {
        get {
            let __value = JNIField.GetStaticIntField( fieldName: "NORM_PRIORITY", fieldType: "I", fieldCache: &NORM_PRIORITY_FieldID, className: "java/lang/Thread", classCache: &JavaThreadJNIClass )
            return Int(__value)
        }
    }

    /// private static final java.lang.RuntimePermission java.lang.Thread.SUBCLASS_IMPLEMENTATION_PERMISSION

    /// private static volatile java.lang.Thread$UncaughtExceptionHandler java.lang.Thread.defaultUncaughtExceptionHandler

    /// private static int java.lang.Thread.threadInitNumber

    /// private static long java.lang.Thread.threadSeqNumber

    /// private volatile sun.nio.ch.Interruptible java.lang.Thread.blocker

    /// private final java.lang.Object java.lang.Thread.blockerLock

    /// private java.lang.ClassLoader java.lang.Thread.contextClassLoader

    /// private boolean java.lang.Thread.daemon

    /// private long java.lang.Thread.eetop

    /// private java.lang.ThreadGroup java.lang.Thread.group

    /// java.lang.ThreadLocal$ThreadLocalMap java.lang.Thread.inheritableThreadLocals

    // Skipping field: true false false false false false 

    /// private java.security.AccessControlContext java.lang.Thread.inheritedAccessControlContext

    /// private volatile char[] java.lang.Thread.name

    /// private long java.lang.Thread.nativeParkEventPointer

    /// volatile java.lang.Object java.lang.Thread.parkBlocker

    // Skipping field: true false false false false false 

    /// private int java.lang.Thread.priority

    /// private boolean java.lang.Thread.single_step

    /// private long java.lang.Thread.stackSize

    /// private boolean java.lang.Thread.stillborn

    /// private java.lang.Runnable java.lang.Thread.target

    /// int java.lang.Thread.threadLocalRandomProbe

    // Skipping field: true false false false false false 

    /// int java.lang.Thread.threadLocalRandomSecondarySeed

    // Skipping field: true false false false false false 

    /// long java.lang.Thread.threadLocalRandomSeed

    // Skipping field: true false false false false false 

    /// java.lang.ThreadLocal$ThreadLocalMap java.lang.Thread.threadLocals

    // Skipping field: true false false false false false 

    /// private java.lang.Thread java.lang.Thread.threadQ

    /// private volatile int java.lang.Thread.threadStatus

    /// private long java.lang.Thread.tid

    /// private volatile java.lang.Thread$UncaughtExceptionHandler java.lang.Thread.uncaughtExceptionHandler

    /// public java.lang.Thread()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __object = JNIMethod.NewObject( className: "java/lang/Thread", classCache: &JavaThread.JavaThreadJNIClass, methodSig: "()V", methodCache: &JavaThread.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public java.lang.Thread(java.lang.Runnable)

    private static var new_MethodID_2: jmethodID?

    public convenience init( arg0: Runnable? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/Thread", classCache: &JavaThread.JavaThreadJNIClass, methodSig: "(Ljava/lang/Runnable;)V", methodCache: &JavaThread.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Runnable? ) {
        self.init( arg0: _arg0 )
    }

    /// public java.lang.Thread(java.lang.Runnable,java.lang.String)

    private static var new_MethodID_3: jmethodID?

    public convenience init( arg0: Runnable?, arg1: String? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/Thread", classCache: &JavaThread.JavaThreadJNIClass, methodSig: "(Ljava/lang/Runnable;Ljava/lang/String;)V", methodCache: &JavaThread.new_MethodID_3, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Runnable?, _ _arg1: String? ) {
        self.init( arg0: _arg0, arg1: _arg1 )
    }

    /// java.lang.Thread(java.lang.Runnable,java.security.AccessControlContext)

    // Skipping init: true false false 

    /// public java.lang.Thread(java.lang.String)

    private static var new_MethodID_4: jmethodID?

    public convenience init( arg0: String? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/Thread", classCache: &JavaThread.JavaThreadJNIClass, methodSig: "(Ljava/lang/String;)V", methodCache: &JavaThread.new_MethodID_4, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: String? ) {
        self.init( arg0: _arg0 )
    }

    /// public java.lang.Thread(java.lang.ThreadGroup,java.lang.Runnable)

    private static var new_MethodID_5: jmethodID?

    public convenience init( arg0: /* class java.lang.ThreadGroup */ UnavailableObject?, arg1: Runnable? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/Thread", classCache: &JavaThread.JavaThreadJNIClass, methodSig: "(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;)V", methodCache: &JavaThread.new_MethodID_5, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: /* class java.lang.ThreadGroup */ UnavailableObject?, _ _arg1: Runnable? ) {
        self.init( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.lang.Thread(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String)

    private static var new_MethodID_6: jmethodID?

    public convenience init( arg0: /* class java.lang.ThreadGroup */ UnavailableObject?, arg1: Runnable?, arg2: String? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/Thread", classCache: &JavaThread.JavaThreadJNIClass, methodSig: "(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;Ljava/lang/String;)V", methodCache: &JavaThread.new_MethodID_6, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: /* class java.lang.ThreadGroup */ UnavailableObject?, _ _arg1: Runnable?, _ _arg2: String? ) {
        self.init( arg0: _arg0, arg1: _arg1, arg2: _arg2 )
    }

    /// public java.lang.Thread(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String,long)

    private static var new_MethodID_7: jmethodID?

    public convenience init( arg0: /* class java.lang.ThreadGroup */ UnavailableObject?, arg1: Runnable?, arg2: String?, arg3: Int64 ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 4 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        __args[2] = JNIType.toJava( value: arg2, locals: &__locals )
        __args[3] = jvalue( j: arg3 )
        let __object = JNIMethod.NewObject( className: "java/lang/Thread", classCache: &JavaThread.JavaThreadJNIClass, methodSig: "(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;Ljava/lang/String;J)V", methodCache: &JavaThread.new_MethodID_7, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: /* class java.lang.ThreadGroup */ UnavailableObject?, _ _arg1: Runnable?, _ _arg2: String?, _ _arg3: Int64 ) {
        self.init( arg0: _arg0, arg1: _arg1, arg2: _arg2, arg3: _arg3 )
    }

    /// public java.lang.Thread(java.lang.ThreadGroup,java.lang.String)

    private static var new_MethodID_8: jmethodID?

    public convenience init( arg0: /* class java.lang.ThreadGroup */ UnavailableObject?, arg1: String? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        __args[1] = JNIType.toJava( value: arg1, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/Thread", classCache: &JavaThread.JavaThreadJNIClass, methodSig: "(Ljava/lang/ThreadGroup;Ljava/lang/String;)V", methodCache: &JavaThread.new_MethodID_8, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: /* class java.lang.ThreadGroup */ UnavailableObject?, _ _arg1: String? ) {
        self.init( arg0: _arg0, arg1: _arg1 )
    }

    /// public static int java.lang.Thread.activeCount()

    private static var activeCount_MethodID_9: jmethodID?

    open class func activeCount() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "activeCount", methodSig: "()I", methodCache: &activeCount_MethodID_9, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// private static boolean java.lang.Thread.auditSubclass(java.lang.Class)

    /// public static native java.lang.Thread java.lang.Thread.currentThread()

    private static var currentThread_MethodID_10: jmethodID?

    open class func currentThread() -> JavaThread! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "currentThread", methodSig: "()Ljava/lang/Thread;", methodCache: &currentThread_MethodID_10, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? JavaThread( javaObject: __return ) : nil
    }


    /// public static void java.lang.Thread.dumpStack()

    private static var dumpStack_MethodID_11: jmethodID?

    open class func dumpStack() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallStaticVoidMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "dumpStack", methodSig: "()V", methodCache: &dumpStack_MethodID_11, args: &__args, locals: &__locals )
    }


    /// private static native java.lang.StackTraceElement[][] java.lang.Thread.dumpThreads(java.lang.Thread[])

    /// public static int java.lang.Thread.enumerate(java.lang.Thread[])

    private static var enumerate_MethodID_12: jmethodID?

    open class func enumerate( arg0: [JavaThread]? ) -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticIntMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "enumerate", methodSig: "([Ljava/lang/Thread;)I", methodCache: &enumerate_MethodID_12, args: &__args, locals: &__locals )
        return Int(__return)
    }

    open class func enumerate( _ _arg0: [JavaThread]? ) -> Int {
        return enumerate( arg0: _arg0 )
    }

    /// public static java.util.Map java.lang.Thread.getAllStackTraces()

    private static var getAllStackTraces_MethodID_13: jmethodID?

    open class func getAllStackTraces() -> JavaMap! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "getAllStackTraces", methodSig: "()Ljava/util/Map;", methodCache: &getAllStackTraces_MethodID_13, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: JavaMapForward.self, from: __return )
    }


    /// public static java.lang.Thread$UncaughtExceptionHandler java.lang.Thread.getDefaultUncaughtExceptionHandler()

    private static var getDefaultUncaughtExceptionHandler_MethodID_14: jmethodID?

    open class func getDefaultUncaughtExceptionHandler() -> /* interface java.lang.Thread$UncaughtExceptionHandler */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "getDefaultUncaughtExceptionHandler", methodSig: "()Ljava/lang/Thread$UncaughtExceptionHandler;", methodCache: &getDefaultUncaughtExceptionHandler_MethodID_14, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.lang.Thread$UncaughtExceptionHandler */ UnavailableProtocolForward( javaObject: __return ) : nil
    }


    /// private static native java.lang.Thread[] java.lang.Thread.getThreads()

    /// public static native boolean java.lang.Thread.holdsLock(java.lang.Object)

    private static var holdsLock_MethodID_15: jmethodID?

    open class func holdsLock( arg0: JavaObject? ) -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticBooleanMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "holdsLock", methodSig: "(Ljava/lang/Object;)Z", methodCache: &holdsLock_MethodID_15, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }

    open class func holdsLock( _ _arg0: JavaObject? ) -> Bool {
        return holdsLock( arg0: _arg0 )
    }

    /// public static boolean java.lang.Thread.interrupted()

    private static var interrupted_MethodID_16: jmethodID?

    open class func interrupted() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticBooleanMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "interrupted", methodSig: "()Z", methodCache: &interrupted_MethodID_16, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// private static boolean java.lang.Thread.isCCLOverridden(java.lang.Class)

    /// private static synchronized long java.lang.Thread.nextThreadID()

    /// private static synchronized int java.lang.Thread.nextThreadNum()

    /// static void java.lang.Thread.processQueue(java.lang.ref.ReferenceQueue,java.util.concurrent.ConcurrentMap)

    // Skipping method: true false false false false 

    /// private static native void java.lang.Thread.registerNatives()

    /// public static void java.lang.Thread.setDefaultUncaughtExceptionHandler(java.lang.Thread$UncaughtExceptionHandler)

    private static var setDefaultUncaughtExceptionHandler_MethodID_17: jmethodID?

    open class func setDefaultUncaughtExceptionHandler( arg0: /* interface java.lang.Thread$UncaughtExceptionHandler */ UnavailableProtocol? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallStaticVoidMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "setDefaultUncaughtExceptionHandler", methodSig: "(Ljava/lang/Thread$UncaughtExceptionHandler;)V", methodCache: &setDefaultUncaughtExceptionHandler_MethodID_17, args: &__args, locals: &__locals )
    }

    open class func setDefaultUncaughtExceptionHandler( _ _arg0: /* interface java.lang.Thread$UncaughtExceptionHandler */ UnavailableProtocol? ) {
        setDefaultUncaughtExceptionHandler( arg0: _arg0 )
    }

    /// public static native void java.lang.Thread.sleep(long) throws java.lang.InterruptedException

    private static var sleep_MethodID_18: jmethodID?

    open class func sleep( arg0: Int64 ) throws /* java.lang.InterruptedException */ {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( j: arg0 )
        JNIMethod.CallStaticVoidMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "sleep", methodSig: "(J)V", methodCache: &sleep_MethodID_18, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            defer { JNI.DeleteLocalRef( throwable ) }
            throw /* class java.lang.InterruptedException */ UnavailableObject( javaObject: throwable )
        }
    }

    open class func sleep( _ _arg0: Int64 ) throws /* java.lang.InterruptedException */ {
        try sleep( arg0: _arg0 )
    }

    /// public static void java.lang.Thread.sleep(long,int) throws java.lang.InterruptedException

    private static var sleep_MethodID_19: jmethodID?

    open class func sleep( arg0: Int64, arg1: Int ) throws /* java.lang.InterruptedException */ {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = jvalue( j: arg0 )
        __args[1] = jvalue( i: jint(arg1) )
        JNIMethod.CallStaticVoidMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "sleep", methodSig: "(JI)V", methodCache: &sleep_MethodID_19, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            defer { JNI.DeleteLocalRef( throwable ) }
            throw /* class java.lang.InterruptedException */ UnavailableObject( javaObject: throwable )
        }
    }

    open class func sleep( _ _arg0: Int64, _ _arg1: Int ) throws /* java.lang.InterruptedException */ {
        try sleep( arg0: _arg0, arg1: _arg1 )
    }

    /// public static native void java.lang.Thread.yield()

    private static var yield_MethodID_20: jmethodID?

    open class func yield() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallStaticVoidMethod( className: "java/lang/Thread", classCache: &JavaThreadJNIClass, methodName: "yield", methodSig: "()V", methodCache: &yield_MethodID_20, args: &__args, locals: &__locals )
    }


    /// private void java.lang.Thread.init(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String,long)

    /// private void java.lang.Thread.init(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String,long,java.security.AccessControlContext)

    /// void java.lang.Thread.blockedOn(sun.nio.ch.Interruptible)

    // Skipping method: true false false false false 

    /// public final void java.lang.Thread.checkAccess()

    private static var checkAccess_MethodID_21: jmethodID?

    open func checkAccess() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "checkAccess", methodSig: "()V", methodCache: &JavaThread.checkAccess_MethodID_21, args: &__args, locals: &__locals )
    }


    /// protected java.lang.Object java.lang.Thread.clone() throws java.lang.CloneNotSupportedException

    private static var clone_MethodID_22: jmethodID?

    override open func clone() throws /* java.lang.CloneNotSupportedException */ -> JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "clone", methodSig: "()Ljava/lang/Object;", methodCache: &JavaThread.clone_MethodID_22, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        if let throwable = JNI.ExceptionCheck() {
            defer { JNI.DeleteLocalRef( throwable ) }
            throw /* class java.lang.CloneNotSupportedException */ UnavailableObject( javaObject: throwable )
        }
        return __return != nil ? JavaObject( javaObject: __return ) : nil
    }


    /// public native int java.lang.Thread.countStackFrames()

    private static var countStackFrames_MethodID_23: jmethodID?

    open func countStackFrames() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "countStackFrames", methodSig: "()I", methodCache: &JavaThread.countStackFrames_MethodID_23, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public void java.lang.Thread.destroy()

    private static var destroy_MethodID_24: jmethodID?

    open func destroy() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "destroy", methodSig: "()V", methodCache: &JavaThread.destroy_MethodID_24, args: &__args, locals: &__locals )
    }


    /// private void java.lang.Thread.dispatchUncaughtException(java.lang.Throwable)

    /// private void java.lang.Thread.exit()

    /// public java.lang.ClassLoader java.lang.Thread.getContextClassLoader()

    private static var getContextClassLoader_MethodID_25: jmethodID?

    open func getContextClassLoader() -> /* class java.lang.ClassLoader */ UnavailableObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getContextClassLoader", methodSig: "()Ljava/lang/ClassLoader;", methodCache: &JavaThread.getContextClassLoader_MethodID_25, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* class java.lang.ClassLoader */ UnavailableObject( javaObject: __return ) : nil
    }


    /// public long java.lang.Thread.getId()

    private static var getId_MethodID_26: jmethodID?

    open func getId() -> Int64 {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallLongMethod( object: javaObject, methodName: "getId", methodSig: "()J", methodCache: &JavaThread.getId_MethodID_26, args: &__args, locals: &__locals )
        return __return
    }


    /// public final java.lang.String java.lang.Thread.getName()

    private static var getName_MethodID_27: jmethodID?

    open func getName() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getName", methodSig: "()Ljava/lang/String;", methodCache: &JavaThread.getName_MethodID_27, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public final int java.lang.Thread.getPriority()

    private static var getPriority_MethodID_28: jmethodID?

    open func getPriority() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getPriority", methodSig: "()I", methodCache: &JavaThread.getPriority_MethodID_28, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public java.lang.StackTraceElement[] java.lang.Thread.getStackTrace()

    private static var getStackTrace_MethodID_29: jmethodID?

    open func getStackTrace() -> [/* class java.lang.StackTraceElement */ UnavailableObject]! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getStackTrace", methodSig: "()[Ljava/lang/StackTraceElement;", methodCache: &JavaThread.getStackTrace_MethodID_29, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [/* class java.lang.StackTraceElement */ UnavailableObject].self, from: __return )
    }


    /// public java.lang.Thread$State java.lang.Thread.getState()

    private static var getState_MethodID_30: jmethodID?

    open func getState() -> /* class java.lang.Thread$State */ UnavailableEnum! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getState", methodSig: "()Ljava/lang/Thread$State;", methodCache: &JavaThread.getState_MethodID_30, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* class java.lang.Thread$State */ UnavailableEnum( javaObject: __return ) : nil
    }


    /// public final java.lang.ThreadGroup java.lang.Thread.getThreadGroup()

    private static var getThreadGroup_MethodID_31: jmethodID?

    open func getThreadGroup() -> /* class java.lang.ThreadGroup */ UnavailableObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getThreadGroup", methodSig: "()Ljava/lang/ThreadGroup;", methodCache: &JavaThread.getThreadGroup_MethodID_31, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* class java.lang.ThreadGroup */ UnavailableObject( javaObject: __return ) : nil
    }


    /// public java.lang.Thread$UncaughtExceptionHandler java.lang.Thread.getUncaughtExceptionHandler()

    private static var getUncaughtExceptionHandler_MethodID_32: jmethodID?

    open func getUncaughtExceptionHandler() -> /* interface java.lang.Thread$UncaughtExceptionHandler */ UnavailableProtocol! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getUncaughtExceptionHandler", methodSig: "()Ljava/lang/Thread$UncaughtExceptionHandler;", methodCache: &JavaThread.getUncaughtExceptionHandler_MethodID_32, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? /* interface java.lang.Thread$UncaughtExceptionHandler */ UnavailableProtocolForward( javaObject: __return ) : nil
    }


    /// public void java.lang.Thread.interrupt()

    private static var interrupt_MethodID_33: jmethodID?

    open func interrupt() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "interrupt", methodSig: "()V", methodCache: &JavaThread.interrupt_MethodID_33, args: &__args, locals: &__locals )
    }


    /// private native void java.lang.Thread.interrupt0()

    /// public final native boolean java.lang.Thread.isAlive()

    private static var isAlive_MethodID_34: jmethodID?

    open func isAlive() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isAlive", methodSig: "()Z", methodCache: &JavaThread.isAlive_MethodID_34, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// public final boolean java.lang.Thread.isDaemon()

    private static var isDaemon_MethodID_35: jmethodID?

    open func isDaemon() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isDaemon", methodSig: "()Z", methodCache: &JavaThread.isDaemon_MethodID_35, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// private native boolean java.lang.Thread.isInterrupted(boolean)

    /// public boolean java.lang.Thread.isInterrupted()

    private static var isInterrupted_MethodID_36: jmethodID?

    open func isInterrupted() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isInterrupted", methodSig: "()Z", methodCache: &JavaThread.isInterrupted_MethodID_36, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// public final synchronized void java.lang.Thread.join(long) throws java.lang.InterruptedException

    private static var join_MethodID_37: jmethodID?

    open func join( arg0: Int64 ) throws /* java.lang.InterruptedException */ {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( j: arg0 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "join", methodSig: "(J)V", methodCache: &JavaThread.join_MethodID_37, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            defer { JNI.DeleteLocalRef( throwable ) }
            throw /* class java.lang.InterruptedException */ UnavailableObject( javaObject: throwable )
        }
    }

    open func join( _ _arg0: Int64 ) throws /* java.lang.InterruptedException */ {
        try join( arg0: _arg0 )
    }

    /// public final synchronized void java.lang.Thread.join(long,int) throws java.lang.InterruptedException

    private static var join_MethodID_38: jmethodID?

    open func join( arg0: Int64, arg1: Int ) throws /* java.lang.InterruptedException */ {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = jvalue( j: arg0 )
        __args[1] = jvalue( i: jint(arg1) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "join", methodSig: "(JI)V", methodCache: &JavaThread.join_MethodID_38, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            defer { JNI.DeleteLocalRef( throwable ) }
            throw /* class java.lang.InterruptedException */ UnavailableObject( javaObject: throwable )
        }
    }

    open func join( _ _arg0: Int64, _ _arg1: Int ) throws /* java.lang.InterruptedException */ {
        try join( arg0: _arg0, arg1: _arg1 )
    }

    /// public final void java.lang.Thread.join() throws java.lang.InterruptedException

    private static var join_MethodID_39: jmethodID?

    open func join() throws /* java.lang.InterruptedException */ {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "join", methodSig: "()V", methodCache: &JavaThread.join_MethodID_39, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            defer { JNI.DeleteLocalRef( throwable ) }
            throw /* class java.lang.InterruptedException */ UnavailableObject( javaObject: throwable )
        }
    }


    /// public final void java.lang.Thread.resume()

    private static var resume_MethodID_40: jmethodID?

    open func resume() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "resume", methodSig: "()V", methodCache: &JavaThread.resume_MethodID_40, args: &__args, locals: &__locals )
    }


    /// private native void java.lang.Thread.resume0()

    /// public void java.lang.Thread.run()

    private static var run_MethodID_41: jmethodID?

    open func run() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "run", methodSig: "()V", methodCache: &JavaThread.run_MethodID_41, args: &__args, locals: &__locals )
    }


    /// public void java.lang.Thread.setContextClassLoader(java.lang.ClassLoader)

    private static var setContextClassLoader_MethodID_42: jmethodID?

    open func setContextClassLoader( arg0: /* class java.lang.ClassLoader */ UnavailableObject? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setContextClassLoader", methodSig: "(Ljava/lang/ClassLoader;)V", methodCache: &JavaThread.setContextClassLoader_MethodID_42, args: &__args, locals: &__locals )
    }

    open func setContextClassLoader( _ _arg0: /* class java.lang.ClassLoader */ UnavailableObject? ) {
        setContextClassLoader( arg0: _arg0 )
    }

    /// public final void java.lang.Thread.setDaemon(boolean)

    private static var setDaemon_MethodID_43: jmethodID?

    open func setDaemon( arg0: Bool ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( z: jboolean(arg0 ? JNI_TRUE : JNI_FALSE) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setDaemon", methodSig: "(Z)V", methodCache: &JavaThread.setDaemon_MethodID_43, args: &__args, locals: &__locals )
    }

    open func setDaemon( _ _arg0: Bool ) {
        setDaemon( arg0: _arg0 )
    }

    /// public final synchronized void java.lang.Thread.setName(java.lang.String)

    private static var setName_MethodID_44: jmethodID?

    open func setName( arg0: String? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setName", methodSig: "(Ljava/lang/String;)V", methodCache: &JavaThread.setName_MethodID_44, args: &__args, locals: &__locals )
    }

    open func setName( _ _arg0: String? ) {
        setName( arg0: _arg0 )
    }

    /// private native void java.lang.Thread.setNativeName(java.lang.String)

    /// public final void java.lang.Thread.setPriority(int)

    private static var setPriority_MethodID_45: jmethodID?

    open func setPriority( arg0: Int ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( i: jint(arg0) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setPriority", methodSig: "(I)V", methodCache: &JavaThread.setPriority_MethodID_45, args: &__args, locals: &__locals )
    }

    open func setPriority( _ _arg0: Int ) {
        setPriority( arg0: _arg0 )
    }

    /// private native void java.lang.Thread.setPriority0(int)

    /// public void java.lang.Thread.setUncaughtExceptionHandler(java.lang.Thread$UncaughtExceptionHandler)

    private static var setUncaughtExceptionHandler_MethodID_46: jmethodID?

    open func setUncaughtExceptionHandler( arg0: /* interface java.lang.Thread$UncaughtExceptionHandler */ UnavailableProtocol? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setUncaughtExceptionHandler", methodSig: "(Ljava/lang/Thread$UncaughtExceptionHandler;)V", methodCache: &JavaThread.setUncaughtExceptionHandler_MethodID_46, args: &__args, locals: &__locals )
    }

    open func setUncaughtExceptionHandler( _ _arg0: /* interface java.lang.Thread$UncaughtExceptionHandler */ UnavailableProtocol? ) {
        setUncaughtExceptionHandler( arg0: _arg0 )
    }

    /// public synchronized void java.lang.Thread.start()

    private static var start_MethodID_47: jmethodID?

    open func start() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "start", methodSig: "()V", methodCache: &JavaThread.start_MethodID_47, args: &__args, locals: &__locals )
    }


    /// private native void java.lang.Thread.start0()

    /// public final synchronized void java.lang.Thread.stop(java.lang.Throwable)

    private static var stop_MethodID_48: jmethodID?

    open func stop( arg0: Throwable? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "stop", methodSig: "(Ljava/lang/Throwable;)V", methodCache: &JavaThread.stop_MethodID_48, args: &__args, locals: &__locals )
    }

    open func stop( _ _arg0: Throwable? ) {
        stop( arg0: _arg0 )
    }

    /// public final void java.lang.Thread.stop()

    private static var stop_MethodID_49: jmethodID?

    open func stop() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "stop", methodSig: "()V", methodCache: &JavaThread.stop_MethodID_49, args: &__args, locals: &__locals )
    }


    /// private native void java.lang.Thread.stop0(java.lang.Object)

    /// public final void java.lang.Thread.suspend()

    private static var suspend_MethodID_50: jmethodID?

    open func suspend() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "suspend", methodSig: "()V", methodCache: &JavaThread.suspend_MethodID_50, args: &__args, locals: &__locals )
    }


    /// private native void java.lang.Thread.suspend0()

    /// public java.lang.String java.lang.Thread.toString()

    // Skipping method: false true false false false 

}

